name: Jekyll site CI

on:
  push:
    branches: [ "main" ]  # Change to gh-pages if you want to deploy from there
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up gem credentials
      run: |
        echo "//your-private-gem-registry.com/:_authToken=${{ secrets.REGISTRY_TOKEN }}" > ~/.gem/credentials
        chmod 600 ~/.gem/credentials

    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

    - name: Deploy to GitHub Pages
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./_site
