name: Deploy Jekyll site to Pages

on:
  push:
    branches: [ "main" ]  # Triggers the workflow on pushes to the 'main' branch
  workflow_dispatch:  # Allows manual triggering from the Actions tab

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3  # Use the latest version of checkout

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1  # Use the latest stable version of ruby/setup-ruby
        with:
          ruby-version: '3.1'  # Ensure this matches your Ruby version in Gemfile
          bundler-cache: true  # Caches installed gems
          cache-version: 0  # Increment this number if you need to re-download cached gems

      - name: Build with Jekyll
        run: |
          gem install bundler
          bundle install
          bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1  # Use the latest version of upload-pages-artifact
        with:
          path: ./_site  # Path to the Jekyll build output

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}  # URL of the deployed site
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1  # Use the latest version of deploy-pages
